name: Custom trigger test
on:
  issue_comment:
    types: [created]

jobs:
  test:
    if: github.event.issue.pull_request && github.event.comment.body == '/test'
    uses: vprashar2929/kepler/.github/workflows/dummy.yml@main
    with:
      pr: "1234"
