name: Custom trigger test
on:
  issue_comment:
    types: [created]

jobs:
  test:
    if: github.event.issue.pull_request && github.event.comment.body == '/test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test step
        run: echo "This is a test"

      - name: get the pr number
        run: echo "pr_number=${{ github.event.pull_request.head.sha }}"

      - name: Check Event JSON
        run: echo "${{ toJson(github.event) }}"

